# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('account_number', models.TextField(null=True)),
                ('currency', models.TextField(null=True)),
            ],
        ),
    ]
