# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default='unknown', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
