# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('quantity', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('note', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.Symbol')),
            ],
        ),
    ]
