# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='value',
            new_name='amount',
        ),
    ]
