# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171214_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.TextField(db_index=True, default='unknown'),
            preserve_default=False,
        ),
    ]
